export default [
  {
    id: 1,
    title: "Kalimba",
    artist: "Mr. Scruff",
    url: "./media/kalimba.mp3",
    img: "./Images/Kalimba.jpg",
  },
  {
    id: 2,
    title: "Maid with the Flaxen Hair",
    artist: "Richard Stoltzman",
    url: "./media/Maid with the Flaxen Hair.mp3",
    img: "./Images/Maid with the Flaxen Hair.jpg",
  },
  {
    id: 3,
    title: "Sleep Away",
    artist: "Bob Acri",
    url: "./media/Sleep Away.mp3",
    img: "./Images/Sleep Away.jpg",
  },
  {
    id: 4,
    title: "Harley Bird - Home",
    artist: "Jordan Schor",
    url: "./media/Harley Bird - Home.mp3",
    img: "./Images/Harley Bird - Home.jpg",
  },
  {
    id: 5,
    title: "Ikson Anywhere – Ikson",
    artist: "Audio Library",
    url: "./media/Ikson Anywhere – Ikson.mp3",
    img: "./Images/Ikson Anywhere – Ikson.jpg",
  },
  {
    id: 6,
    title: "Beauz & Jvna - Crazy",
    artist: "Beauz & Jvna",
    url: "./media/Beauz & Jvna - Crazy.mp3",
    img: "./Images/Beauz & Jvna - Crazy.jpg",
  },
  {
    id: 7,
    title: "Hardwind - Want Me",
    artist: "Mike Archangelo",
    url: "./media/Hardwind - Want Me.mp3",
    img: "./Images/Hardwind - Want Me.jpg",
  },
  {
    id: 8,
    title: "Jim - Sun Goes Down",
    artist: "Jim Yosef x Roy",
    url: "./media/Jim - Sun Goes Down.mp3",
    img: "./Images/Jim - Sun Goes Down.jpg",
  },
  {
    id: 9,
    title: "Lost Sky - Vision NCS",
    artist: "NCS Release",
    url: "./media/Lost Sky - Vision NCS.mp3",
    img: "./Images/Lost Sky - Vision NCS.jpg",
  },
];
